on right click with a gold nugget:
	# Check if the cooldown for the player is active.
	if is_on_cooldown("ding", player) is true:

		set {_remaining_cooldown} to get_remaining_cooldown("ding", player)
		send formatted "%get_mib_color("error")%You must wait %{_remaining_cooldown}% before using this again." to player
		stop

	# Set the cooldown for the player to 5 seconds.
	set_cooldown("ding", 5 seconds, player)
	play sound "minecraft:block.note_block.bit" to player